# GitHub Pages configuration
theme: minima
plugins:
  - jekyll-relative-links
  - jekyll-seo-tag

# Markdown processing
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Site settings
title: 商業高等学校教員向け 生成AI利活用ツールキット
description: プロンプトエンジニアリングの基礎から実践まで学べる教育資料集
lang: ja

# Exclude files from processing
exclude:
  - README.md
  - LICENSE
  - .gitignore